services:
  postgres:
    image: postgres:15
    container_name: oficina_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: oficina
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ../oficina-api
    ports:
      - "3000:3000"
    volumes:
      - ../oficina-api:/app
      - /app/node_modules
    command: npm run start:dev

  web:
    build: ../oficina-web
    ports:
      - "4200:4200"
    volumes:
      - ../oficina-web:/app
      - /app/node_modules
    command: npm run start

volumes:
  pgdata:
